<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Client\Client.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\**\*.png" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Assets\health_bar.png" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Update="Assets\health_bar.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
</Project>